### ISSUE TITLE
"Catalog" and "Find Objects" tabs in the ZMI

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.ZCatalog#101] opened 2020-05-06 06:50 UTC
At first I thought "Find Objects" does not work, as it returned "There are no objects in the Catalog.". The same is shown in the "Catalog" tab where the catalogued objects used to be displayed in former versions.

I then created a FieldIndex before running another "Find Objects" procedure: although no objects were shown, I could see some data in the "distinct values" column in the "Index" tab.

So the problem seems only to be that the objects are not shown in the ZMI (they can be accessed normally from a script).

**Comment by d-maurer** [comment] 2020-05-06 08:59
Georg Pfolz wrote at 2020-5-5 23:50 -0700:
> ...
>So the problem seems only to be that the objects are not shown in the ZMI (they can be accessed normally from a script).

This bug is caused by a recent change: formerly, an (effectively) empty
search returned all hits; now, it returns 0 hits.
`dtml/catalogView.dtml` (i.e. the implementation of the `Catalog` tab)
is not yet updated to this change.

It is possible that this bug shows itself only when your catalog
has no index named `path`.

**Comment by georgpfolz** [comment] 2020-05-06 09:10
> It is possible that this bug shows itself only when your catalog
> has no index named `path`.

Great, thank you! That works for me :)

**Comment by icemac** [comment] 2020-05-08 14:05
Closing this issue as there is #102 as follow-up.

**Closed by icemac** 2020-05-08 14:05 UTC
